server:
  http_listen_port: 9080
  grpc_listen_port: 0
positions:
  filename: /tmp/positions.yaml
clients:
  - url: http://loki:3100/loki/api/v1/push
scrape_configs:
  - job_name: rclaim-file
    static_configs:
      - targets:
          - localhost
        labels:
          job: rclaim
          __path__: /logs/rclaim.log.*
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            target: target
      - labels:
          level:
          target:
  - job_name: rclaim-docker
    docker:
      host: unix:///var/run/docker.sock
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            target: target
      - labels:
          level:
          target:
